<a href="https://colab.research.google.com/github/panni-rajula/Python-learning/blob/master/panni/lists/starter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


2D array

In [ ]:
import numpy as np
a =np.array([[1,2,3,4,5],[6,7,8,9]])
print(a)

[list([1, 2, 3, 4, 5]) list([6, 7, 8, 9])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


3D array

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


No of dimensions

In [ ]:
import numpy as np
a = np.array(18)
b = np.array([1,2,3])
c= np.array([[1,8,9],[45,67,890]])
d = np.array([[1],[59,5],[25,36,97]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
1


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """


In [ ]:
import numpy as np
a =np.array([1,2,3],ndmin=5)
print(a.ndim)

5


accessing array elements

import numpy as np
a = np.array([1,2,3,56])
print(a[2],a[0])

In [ ]:
import numpy as np
a = np.array([1,2,3,5,8,7,9])
print(a[3]+a[2])

8


accessing 2D elements

In [ ]:
import numpy as np
a=np.array([[1,2,3,6],[7,8,9,54]])
print(a[1,1])

8


negative indexing

In [ ]:
import numpy as np
a=np.array([[1,2,3,6],[7,8,9,54]])
print('Last element from 2nd dimension is:',a[1,-1]) 

Last element from 2nd dimension is: 54


Slicing arrays

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a[1:5])


[[ 7  8  9 54]]


data type of a array

In [ ]:
import numpy as np
a = np.array(['apple','banana','cherry'],dtype='S')
  print(a.dtype)

float64


converting data types

In [ ]:
import numpy as np
a = np.array([1.0,2.5,6.5,8.1])


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)



[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
import numpy as np
arr = np.array([12,23,5],[48,46,45,4])
print(arr.shape)

TypeError: ignored